### ISSUE TITLE
Grails 5 "Accessing config through dot notation is deprecated"

### ISSUE THREAD

**Issue by davidkron** [grails/grails-spring-security-core#616]
Im doing some Grails 4.1.0.M1 testing with some of our applications and I get a lot of warnings:

`org.grails.config.NavigableMap: Accessing config through dot notation is deprecated, and it will be removed in a future release. Use 'config.getProperty(key, targetClass)' instead.`

 A lot of these warnings are caused by the spring-security-core plugin, which should be rewritten to not use deprecated configuration access.

**Comment by puneetbehl** [comment]
Could you please verify if this is still an issue with Grails 5.1.2 and the plugin version 5.0.0-RC1

**Comment by davidkron** [comment]
I just made a test:
-  new application (grails create-app)
- `implementation 'org.grails.plugins:spring-security-core:5.0.0-RC1` added
- root logger level set to `warn`

This still prints some warnings, which seem to be coming from the following code:
https://github.com/grails/grails-spring-security-core/blob/33ede9996d7768d30b1da7fa3972f7ef693b6d02/plugin/src/main/groovy/grails/plugin/springsecurity/ReflectionUtils.groovy#L114-L120

**Comment by duchaoqun** [comment]
Grails 5.1.2
plugin version 5.0.0-RC1

[restartedMain] WARN  org.grails.config.NavigableMap - Accessing config key '[springsecurity]' through dot notation is deprecated, and it will be removed in a future release. Use 'config.getProperty(key, targetClass)' instead.
