### ISSUE TITLE
The version of Spring security used by this plugin is EOL

### ISSUE THREAD

**Issue by sjrd218** [grails/grails-spring-security-core#629]
Spring security 5.1.13.RELEASE is EOL according to their Github page. 
https://github.com/spring-projects/spring-security/tree/5.1.x

Please update this plugin to a version that is not EOL.

**Comment by logantracyo** [comment]
Additional info on [Spring Security EOL status](https://github.com/spring-projects/spring-security/wiki/Spring-Security-Versions#released-versions) (as of 2021-11-05) suggests moving to at least 5.4.x, if not 5.5.x:

|Version|OSS Support Until|Expected End-of-Life|
|---|---|---|
|5.1.x ||October 2020|
|5.2.x|September 2020|December 2021|
|5.3.x|May 2021|December 2021|
|5.4.x|October 2021|July 2022|
|5.5.x|May 2022|February 2023|

I'm not likely to have time to take the lead on this upgrade, but could help out someone else . . .

**Comment by puneetbehl** [comment]
Could you please try plugin version 5.0.0-RC1?

**Comment by sjrd218** [comment]
5.0.0-RC1 looks like it works. 

This plugin seems to use dot notation to access configs, which results in a large number of WARN messages in the console, but it doesn't appear to interfere with how it works.

**Comment by puneetbehl** [comment]
Thanks, there is a separate issue to track dot notation warnings. See #616
